### ISSUE TITLE
model_constructor error

### ISSUE THREAD

**Issue by dirknbr** [adamhaber/stan2tfp#2]
I get an error with this simple toy example

```

from stan2tfp import Stan2tfp
import seaborn as sns
import matplotlib.pyplot as plt
import arviz as az
import numpy as np

stan_code = """
data  {
  int N;
  real y[N];
  real x[N];	
}

parameters {
  real a;
  real b;
  real<lower=0> sigma;
}

model {
  a ~ normal(0, 1);
  b ~ normal(0, 1);
  sigma ~ gamma(1, 1);
  y ~ normal(a + beta * x, sigma);
}
"""

N = 100
x = np.random.normal(size=N)
y = 10 + x + np.random.normal(size=N)

data = {'N': N, 'x': x, 'y': y}
model = Stan2tfp(stan_model_code=stan_code, data_dict=data)
```

Traceback (most recent call last):
  File "/home/xxx/python/stan2ftp/test.py", line 36, in <module>
    model = Stan2tfp(stan_model_code=stan_code, data_dict=data)
  File "/home/xxx/.local/lib/python3.8/site-packages/stan2tfp/stan2tfp.py", line 121, in __init__
    self.model_constructor = exec_dict["model"]
KeyError: 'model'

**Comment by adamhaber** [comment]
Thanks for reporting this! What happens is that the Stan file doesn't compile; `stan2tfp` should definitely capture and report these error messages.

The file doesn't compile for two reasons:

1. In `y ~ normal(a + beta * x, sigma);`, `beta` isn't defined. I assume this should `b`?
2. In the same expression, `x` is an array, not a vector, and multiplying it by a scalar isn't defined. Changing `x` and `y` to vectors should do the job:
```stan
data  {
  int N;
  vector[N] y;
  vector[N] x;	
}

parameters {
  real a;
  real b;
  real<lower=0> sigma;
}

model {
  a ~ normal(0, 1);
  b ~ normal(0, 1);
  sigma ~ gamma(1, 1);
  y ~ normal(a + b * x, sigma);
}
```

**Comment by dirknbr** [comment]
Thanks Adam, silly mistakes from my side.
